# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Retrieve npm cache (if any)
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-packages

      # Runs a single command using the runners shell
      - name: Install requesite packages
        working-directory: ./
        run: npm install
      
      - name: Install packages for firebase functions
        working-directory: ./functions
        run: npm install
      
      - name: Convert GitHub Secrets to Firebase Environment Variables
        run: npm run update_keys -- api_key=${{secrets.API_KEY}} private_key=${{secrets.PRIVATE_KEY}}
      
      - name: Deploy to Firebase
        working-directory: ./
        run: npm run deploy -- --token=${{secrets.FIREBASE_TOKEN}}
